---
namespaceOverride: wcc-1-dev

clusterEnvironment: "kind"
parentProject: "wcc-kind"

sources:
  helm:
    - repoURL: "https://bitbucket.org/popreachinc/wcc.git"
      targetRevision: "CHIP-314-wcc-redis-kafka-and-postgresql"
      path: build/helm/redis-cluster
      valueFiles:
        - $values/deploy/k8s/apps/redis-cluster/kind-values.yaml
  git:
    - repoURL: "https://bitbucket.org/popreachinc/wcc.git"
      targetRevision: "CHIP-314-wcc-redis-kafka-and-postgresql"
      ref: values
