---
namespaceOverride: wcc-1-dev

clusterEnvironment: "kind"
parentProject: "wcc-kind"

sources:
  helm:
    - repoURL: "git@github.com:basavaraj23/wcc-parallel.git"
      targetRevision: "main"
      path: build/helm/redis-cluster
      valueFiles:
        - $values/deploy/k8s/apps/redis-cluster/kind-values.yaml
  git:
    - repoURL: "git@github.com:basavaraj23/wcc-parallel.git"
      targetRevision: "main"
      ref: values
