---
namespaceOverride: wcc-1-dev

app:
  name: wcc-postgresql-cluster
  index: 1
  environment: dev

clusterEnvironment: "stg"
parentProject: "wcc-1-dev"

sources:
  helm:
    - repoURL: "git@github.com:basavaraj23/wcc-parallel.git"
      targetRevision: "main"
      path: build/helm/postgresql-cluster
      valueFiles:
        - $values/deploy/k8s/apps/postgresql-cluster/dev-1-values.yaml
  git:
    - repoURL: "git@github.com:basavaraj23/wcc-parallel.git"
      targetRevision: "main"
      ref: values
