apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: wcc-kind
  namespace: argo-1-stg
spec:
  description: Kind cluster applications
  sourceRepos:
    - git@github.com:basavaraj23/wcc-parallel.git
  destinations:
    - namespace: wcc-1-dev
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: wcc-1-dev
  namespace: argo-1-stg
spec:
  description: Dev cluster applications
  sourceRepos:
    - git@github.com:basavaraj23/wcc-parallel.git
  destinations:
    - namespace: wcc-1-dev
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
